in-project: &in-project
  shell_command_before: cd $HOME/code/site

session_name: site
windows:
  - <<: *in-project
    window_name: editor
    panes:
      - eval $EDITOR
  - <<: *in-project
    window_name: jekyll serve
    panes:
      - jekyll serve
